print("programe Excetion Started")
s1=input("Enter First Value:")
s2=input("Enter Second Value:")
a=int(s1)
b=int(s2)
c=a/b
print("Value of a=",a)
print("Value of b=",b)
print("Div=",c)
print("program ended exection")