a=int(input("Enter a value of a:"))
b=int(input("Enter a value of b:"))
print("-"*50)
print("\tArithmetic operators")
print("-"*50)
print("\tsum({},{})={}".format(a,b,a+b))
print("\tsub({},{})={}".format(a,b,a-b))
print("\tmul({},{})={}".format(a,b,a*b))
print("\tdiv({},{})={}".format(a,b,a/b))
print("\F.div({},{})={}".format(a,b,a//b))
print("\tmod({},{})={}".format(a,b,a%b))
print("\tpow({},{})={}".format(a,b,a**b))
